### ISSUE TITLE
Freezing versions for dependencies 

### ISSUE THREAD

**Issue by ska-ibees** [eliasdabbas/advertools#209]
@eliasdabbas  

Currently, versions are not specified for the dependencies mentioned in the [setup.py](https://github.com/eliasdabbas/advertools/blob/93055877b0b2cc14ad59acce6833cf127c462818/setup.py#L14)
Current config:
requirements = [
    'pandas',
    'pyasn1',
    'scrapy',
    'twython',
    'pyarrow',
]

So, on every install, latest versions will be downloaded and installed for these requried packages. 
Instead, we can adopt a common practice by specyfying the required versions to avoid any breaking changes in the newer versions of these dependent packages. 

requirements = [
    'pandas==1.4.2',
    'pyasn1==0.4.8',
    'scrapy==2.6.1',
    'twython==3.9.1',
    'pyarrow==8.0.0',
]

**Comment by eliasdabbas** [comment]
Thanks @ska-ibees 

I've thought about this, and I think it would be a good idea. I've had a few people share bugs that would not have occurred had the right dependencies been specified. 

The dependencies should be specified as minimums `>=` and not exact `==` versions. Users will be using advertools with other packages in their system, and ideally we would want to be as open and flexible as possible. Some project might require pandas version of 1.2 for some reason, while we require `>=1.1`. So, there is no need to add complexity to their project by specifying `==1.4`.

The challenge is to get the lowest possible dependency version, to enable usage by a highest number of users. 

Here is what I remember:

pandas: 1.0 or 1.1 (not sure). We can pin it to `>=1.1.0`
pyasn1: 0.4 (not sure)
`scrapy>=2.5.0` (for using the `response.protocol` attribute)
twython: hasn't been properly updated for a while though, and I'm not sure, we can pin the last version as minimum.

I'll check, and please let me know if you have other thoughts.

**Comment by ska-ibees** [comment]
Thanks for the detailed response. You always come up with better ideas and solutions. 

Agreed on all points you mentioned. There is nothing left for me to add up here. 

Considering my limited knowledge about the feature sets and impacts w.r.t the dependency versions.
I would request you to please take lead on it instead me creating a PR.

**Comment by ska-ibees** [comment]
PR #214
