### ISSUE TITLE
jsonld_sameAs data is mixed with str and list. 

### ISSUE THREAD

**Issue by mirfan899** [eliasdabbas/advertools#219]
Hi. I'm working on a streamlit app and I'm having an issue with scrapped data specifically `jsonld_sameAs` column. It has mixed datatype and streamlit throws error when I try to show the table.

Here is my code
```python
adv.crawl(urls, 'pages.jl', follow_links=False)
crawl_df = pd.read_json('pages.jl', lines=True)
st.dataframe(crawl_df)
```
Here is the error.

```shell
{StreamlitAPIException}('cannot mix list and non-list, non-null values', 'Conversion failed for column jsonld_sameAs with type object')
```

When I checked the datatype of the column it is mixed with str and list. 

![issue](https://user-images.githubusercontent.com/3822565/177035148-508e5b23-cbee-4ae1-ab77-5c74c822f08a.png)

It should be list not str to avoid issues.

**Comment by eliasdabbas** [comment]
Thanks for reporting @mirfan899 

The potential issue with JSON-LD data, is that sometimes, in the same page you have a single element that contains multiple elements. In this case `jsonld_sameAs ` might refer to multiple URLs/entities. 

I suggest you process this column before sending it to streamlit. Maybe:

```python
import pandas as pd
df = pd.DataFrame({
    'a': [['one', 'two', 'three'], 'four', ['five', 'six']],
    'b': [1, 2, 3]
})

df # column a is mixed, string and list:

```
|    | a                       |   b |
|---:|:------------------------|----:|
|  0 | ['one', 'two', 'three'] |   1 |
|  1 | four                    |   2 |
|  2 | ['five', 'six']         |   3 |


```python
df['a_string'] = [x if isinstance(x, str) else ', '.join(x) for x in df['a']]
df
```

|    | a                       |   b | a_string        |
|---:|:------------------------|----:|:----------------|
|  0 | ['one', 'two', 'three'] |   1 | one, two, three |
|  1 | four                    |   2 | four            |
|  2 | ['five', 'six']         |   3 | five, six       |


Let me know if this works, and if you still have an issue.

**Comment by mirfan899** [comment]
Thanks for quick reply. It removes the error on streamlit.

**Comment by eliasdabbas** [comment]
Great. Happy it worked.
Good luck on your app.
