### ISSUE TITLE
No of threads for Crawling

### ISSUE THREAD

**Issue by mirfan899** [eliasdabbas/advertools#228]
Is there a way to specify the no of threads for crawling? Currently it uses all the threads on the system and causes issues to refresh the page.

**Comment by eliasdabbas** [comment]
Can you please clarify?
Crawling almost never does this, at least not that I know of. 
You can check some [crawling recipes](https://advertools.readthedocs.io/en/master/advertools.code_recipes.spider_strategies.html#how-can-i-control-the-number-of-concurrent-requests-while-crawling) here for how to control the number of concurrent requests and so on. 

What code are you running?

**Comment by mirfan899** [comment]
I'm running it on streamlit.

**Comment by eliasdabbas** [comment]
I'm not sure what limitations Streamlit has. You can check their documentation or ask there.

If you want an answer you need to provide full details and code so I can look into it. Otherwise I can't. 

Good luck.
