### ISSUE TITLE
Bulk robots.txt Tester Documentation

### ISSUE THREAD

**Issue by karlolukic** [eliasdabbas/advertools#233]
Hi,

Thanks so much for providing such a valuable Python package to marketing researchers. 

I tried running the `robotstxt_test()` function as described in [documetation](https://advertools.readthedocs.io/en/master/advertools.robotstxt.html#bulk-robots-txt-tester), but the example does not work correctly. I propose the following solution (3rd example below) and a change of the [documetation](https://advertools.readthedocs.io/en/master/advertools.robotstxt.html#bulk-robots-txt-tester):

```
# 1. current example includes wrong syntax
robotstxt_test('https://www.example.com/robots.txt',
               useragents=['Googlebot', 'baiduspider', 'Bingbot']
               urls=['/', '/hello', '/some-page.html']])

# 2. example includes right syntax but does not return meaningful information (i.e., returns HTTP Error 404)
adv.robotstxt_test('https://www.example.com/robots.txt',
               user_agents=['Googlebot', 'baiduspider', 'Bingbot'],
               urls=['/', '/hello', '/some-page.html'])

# 3. example includes right syntax and returns meaningful information
adv.robotstxt_test('https://www.amazon.com/robots.txt',
               user_agents=['Googlebot', 'baiduspider', 'Bingbot'],
               urls=['/', '/hello', '/some-page.html'])
```

**Comment by eliasdabbas** [comment]
Thanks a lot @karlolukic and sorry for the mistake. 

Yes, `user_agents` should contain the underscore, and it assumes that you have imported that function, as opposed to `import advertools as adv`. 

Feel free to submit a pull request for this fix, and I'd love any suggestions on how to improve the documentation. 

You can share the suggested new approach and/or prepare the text and we can review it, whichever you prefer.

**Comment by eliasdabbas** [comment]
I just made the changes. Thanks again @karlolukic.
