### ISSUE TITLE
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. 

### ISSUE THREAD

**Issue by mktgbill** [eliasdabbas/advertools#236]
In the sitemaps extraction script there's a relatively new warning 

FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sitemap_df = sitemap_df.append(elem_df, ignore_index=True)

Thanks,
Bill

**Comment by eliasdabbas** [comment]
Thanks @mktgbill 

This should have been fixed by advertools version 0.13.1

Can you please check which version you have?

Please let me know if you still get this warning on v0.13.1.

**Comment by eliasdabbas** [comment]
Assuming this is working with v0.13.1, so I'm closing this issue. 

Feel free to reopen if you are still getting the warning.
