### ISSUE TITLE
crawl dataFrame - jsonld objects

### ISSUE THREAD

**Issue by dreaded369** [eliasdabbas/advertools#251]
I've made it as far as examining the dataFrame returned from a crawl! 

Looking through the docs I was expecting separately labelled columns for the various bits of jsonls data. Instead I'm seeing a column with lots of Objects within it. Is this a quirk of viewing a datFrame within VSCode? Or are the docs out of date? Or something else? I'm a little stuck!

Thanks!

**Comment by dreaded369** [comment]
Okay - yes its just vscode presenting them as mysterious objects - printing them reveals its multiple json items.

**Comment by eliasdabbas** [comment]
Great. Glad it worked! 

Keep in mind that in some cases a single JSON-LD object on one page might contain multiple items (multiple `sameAs` values for example). This would be represented as a list in a single cell (which can be expanded to a data frame).

You can also try using Jupyter notebook within VSCode (if you aren't already). You can always save the dataframe as a CSV file with the `df.to_csv` method.
