### ISSUE TITLE
Need some way to rate limit requests for sitemap_to_df

### ISSUE THREAD

**Issue by Euphorbium** [eliasdabbas/advertools#270]
When trying to retrieve a large recursive sitemap, I am getting http error 429, too many requests. Currently it seems like there is no way to limit the number of requests it makes, specify a cooldown period or limit the speed of requests. So nothing is ever retrieved with that function.

**Comment by eliasdabbas** [comment]
You can do one of the following: 

* Use the `max_workers` parameter: This defaults to 8, and can be modified to change the number of concurrent requests made. You might set it to 1 to make a single request at a time.

* Download sitemaps individually by first setting `recursive=False`:

```python
import advertools as adv
sitemap = adv.sitemap_to_df(SITEMAP_URL, recursive=False)
```

Now you have all the URLs of the sub-sitemaps, and you can download them individually while introducing intervals between them.

```python
import time
sitemap_df_list = []

for sitemap_url in sitemap['loc']:
    tempdf = adv.sitemap_to_df(sitemap_url)
    sitemap_df_list.append(tempdf)
    time.sleep(60)

all_sitemaps = pd.concat(sitemap_df_list, ignore_index=False)
```
* If your user agent is not being accepted, you can change it (together with any request header) as follows: 

```python
adv.sitemaps.headers['User-Agent'] = 'YOUR-USER-AGENT'
```

Hope this solves it.

**Comment by Euphorbium** [comment]
I did download them manually, but the advertools was useless for me. 1 worker is still too fast, and there is no way to specify rate limiting without doing it myself.On 2023-03-05, at 14:39, Elias Dabbas ***@***.***> wrote:﻿
You can do one of the following:


Use the max_workers parameter: This defaults to 8, and can be modified to change the number of concurrent requests made. You might set it to 1 to make a single request at a time.


Download sitemaps individually by first setting recursive=False:


import advertools as adv
sitemap = adv.sitemap_to_df(SITEMAP_URL, recursive=False)
Now you have all the URLs of the sub-sitemaps, and you can download them individually while introducing intervals between them.
import time
sitemap_df_list = []

for sitemap_url in sitemap['loc']:
    tempdf = adv.sitemap_to_df(sitemap_url)
    sitemap_df_list.append(tempdf)
    time.sleep(60)

all_sitemaps = pd.concat(sitemap_df_list, ignore_index=False)

If your user agent is not being accepted, you can change it (together with any request header) as follows:

adv.sitemaps.headers['User-Agent'] = 'YOUR-USER-AGENT'
Hope this solves it.

**Comment by eliasdabbas** [comment]
Did you try the third approach, where you get the sitemap URLs from the sitemapindex  with `recursive=False` and then introduce `time.sleep`?
