### ISSUE TITLE
no output_file.jl

### ISSUE THREAD

**Issue by senmad** [eliasdabbas/advertools#302]
![test-ipynb-JupyterLab (1)](https://github.com/eliasdabbas/advertools/assets/119980556/b4a4c2b5-8aef-437f-8275-25692bd90ee8)

 I've ran this simple script on 
**google colab ,kaggle, and jupyter lab**
**tried chrome firefox browsers** 
when using job_directory setting ,there are two files about request but

I used log_file setting >

> 2023-08-29 22:34:43 [scrapy.utils.log] INFO: Scrapy 2.10.0 started (bot: scrapybot)
> 2023-08-29 22:34:43 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 23.8.0, Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)], pyOpenSSL 23.2.0 (OpenSSL 3.1.2 1 Aug 2023), cryptography 41.0.3, Platform Windows-10-10.0.19045-SP0
> 2023-08-29 22:34:44 [numexpr.utils] INFO: NumExpr defaulting to 4 threads.
> 2023-08-29 22:34:46 [scrapy.addons] INFO: Enabled addons:
> []
> 2023-08-29 22:34:46 [scrapy.crawler] INFO: Overridden settings:
> {'LOG_FILE': 'example-2.log',
>  'ROBOTSTXT_OBEY': True,
>  'SPIDER_LOADER_WARN_ONLY': True,
>  'USER_AGENT': 'advertools/0.13.5'}
> 2023-08-29 22:34:46 [py.warnings] WARNING: C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\scrapy\utils\request.py:248: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.
> 
> It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.
> 
> See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
>   return cls(crawler)
> 
> 2023-08-29 22:34:46 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.selectreactor.SelectReactor
> 2023-08-29 22:34:46 [scrapy.extensions.telnet] INFO: Telnet Password: b52b36b0eb95f04b
> 2023-08-29 22:34:47 [scrapy.middleware] INFO: Enabled extensions:
> ['scrapy.extensions.corestats.CoreStats',
>  'scrapy.extensions.telnet.TelnetConsole',
>  'scrapy.extensions.feedexport.FeedExporter',
>  'scrapy.extensions.logstats.LogStats']
> 2023-08-29 22:34:47 [scrapy.middleware] INFO: Enabled downloader middlewares:
> ['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
>  'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
>  'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
>  'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
>  'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
>  'scrapy.downloadermiddlewares.retry.RetryMiddleware',
>  'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
>  'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
>  'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
>  'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
>  'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
>  'scrapy.downloadermiddlewares.stats.DownloaderStats']
> 2023-08-29 22:34:47 [scrapy.middleware] INFO: Enabled spider middlewares:
> ['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
>  'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
>  'scrapy.spidermiddlewares.referer.RefererMiddleware',
>  'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
>  'scrapy.spidermiddlewares.depth.DepthMiddleware']
> 2023-08-29 22:34:47 [scrapy.middleware] INFO: Enabled item pipelines:
> []
> 2023-08-29 22:34:47 [scrapy.core.engine] INFO: Spider opened
> 2023-08-29 22:34:47 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
> 2023-08-29 22:34:47 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023

**Comment by eliasdabbas** [comment]
Thanks for reporting @senmad 

Not clear why that is the case. Do you get any output when you run `crawl`? It should output the logs of the crawl, and you should see them on the screen. 

Another possibility might be an issue with one of the dependencies' versions that recently happened.

Can you please try to install this version: 

```bash
!pip install Twisted==22.10.0
```

Also can you please share the versions you are using (advertools, scrapy, twisted). You can get them with:

```python
import twisted
twisted.__version__
```

**Comment by senmad** [comment]
### Wonderful 
_Twisted==22.10.0  was the key_ 
### Thank you
