### ISSUE TITLE
Advertools in Ubuntu in a Venv (Python 3.10.12 and Python 3.9.18)

### ISSUE THREAD

**Issue by mcgaleti** [eliasdabbas/advertools#308]
Hi Everyone,

I am trying to run Advertools in a Python Venv and Ubuntu. 

I tried with the standard Python that comes with this Ubuntu version (3.10.12) and I also tried to install  Python 3.9.18 as I saw someone posting an issue similar and suggesting to use this version *but* the issue is the same.

This is what I did:

mkdir /home/abc/advertools/
cd /home/abc/advertools/
python3 -m venv .
source bin/activate
python3 -m pip install advertools

When I try to type:
adv 
or 
advertools --version

I get

Illegal instruction (core dumped)

Do you guys have some suggestions?

For Python9 I tried:
add-apt-repository ppa:deadsnakes/ppa
apt install python3.9
apt install python3.9-venv
python3.9 -m venv .
source bin/activate
python3 -m pip install advertools

same error:   Illegal instruction (core dumped)

Thank you very much

**Comment by eliasdabbas** [comment]
Thanks for reporting @mcgaleti 

I tried the same series of steps and it seems to work on Ubuntu with Python 3.10

<img width="923" alt="Screen Shot 2023-09-20 at 11 08 38 PM" src="https://github.com/eliasdabbas/advertools/assets/15708966/3a861549-ace0-4160-a8f3-55be0528d3f9">

I'm not sure what is causing this issue. 

One possible thing to change is the name of the directory. It's not good to call the directory "advertools", because it might interfere with how imports work. Maybe try a different directory name?

Please let me know if it works.

**Comment by mcgaleti** [comment]
Hi Elias,

Many thanks for answering very quickly. 

Trying one more time, and if you don't have any other idea, that is fine - I will go with Goggle Colab 

... but I will give it another try:

-Trying with root:

root@hanew:/home# cd /root
root@hanew:~# mkdir digital
root@hanew:~# cd digital/
root@hanew:~/digital# python3.10 -m venv .
root@hanew:~/digital# source bin/activate
(digital) root@hanew:~/digital# python3 -m pip install advertools -q
(digital) root@hanew:~/digital# adv --version
Illegal instruction (core dumped)
(digital) root@hanew:~/digital# advertools --version
Illegal instruction (core dumped)
(digital) root@hanew:~/digital# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy


Now, Trying with my user and python3 instead of 3.10 in a way to try to get whatever python the system is using:

mcgaleti@hanew2:~$ mkdir digital
mcgaleti@hanew2:~$ cd digital
mcgaleti@hanew2:~/digital$ python3 -m venv .
mcgaleti@hanew2:~/digital$ source bin/activate
(digital) mcgaleti@hanew2:~/digital$ python3 -m pip install advertools -q
(digital) mcgaleti@hanew2:~/digital$ adv --version
Illegal instruction (core dumped)
(digital) mcgaleti@hanew2:~/digital$ advertools --version
Illegal instruction (core dumped)
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy


I might be missing some dependency!!  

Thank you

**Comment by mcgaleti** [comment]
Hi Elias,

Many thanks for answering very quickly. 

Trying one more time, and if you don't have any other idea, that is fine - I will go with Google Colab 

... but I will give it another try:

-Trying with root:

root@hanew:/home# cd /root
root@hanew:~# mkdir digital
root@hanew:~# cd digital/
root@hanew:~/digital# python3.10 -m venv .
root@hanew:~/digital# source bin/activate
(digital) root@hanew:~/digital# python3 -m pip install advertools -q
(digital) root@hanew:~/digital# adv --version
Illegal instruction (core dumped)
(digital) root@hanew:~/digital# advertools --version
Illegal instruction (core dumped)
(digital) root@hanew:~/digital# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy


Now, Trying with my user and python3 instead of 3.10 in a way to try to get whatever python the system is using:

mcgaleti@hanew2:~$ mkdir digital
mcgaleti@hanew2:~$ cd digital
mcgaleti@hanew2:~/digital$ python3 -m venv .
mcgaleti@hanew2:~/digital$ source bin/activate
(digital) mcgaleti@hanew2:~/digital$ python3 -m pip install advertools -q
(digital) mcgaleti@hanew2:~/digital$ adv --version
Illegal instruction (core dumped)
(digital) mcgaleti@hanew2:~/digital$ advertools --version
Illegal instruction (core dumped)
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy


I might be missing some dependency!!  

Thank you

**Comment by eliasdabbas** [comment]
Strange...

Is this on your local machine or on server? 

Maybe something with the dependencies? 

Can you please run `pip freeze` and share the output?

**Comment by mcgaleti** [comment]
Hi Elias, 

It's mine small Linux environment. A small DELL where I have Home Assistant and stuff. 

This is the pip freeze output:

(digital) root@hanew:~/digital# pip freeze
advertools==0.13.5
attrs==23.1.0
Automat==22.10.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
constantly==15.1.0
cryptography==41.0.4
cssselect==1.2.0
filelock==3.12.4
hyperlink==21.0.0
idna==3.4
incremental==22.10.0
itemadapter==0.8.0
itemloaders==1.1.0
jmespath==1.0.1
lxml==4.9.3
numpy==1.26.0
oauthlib==3.2.2
packaging==23.1
pandas==2.1.1
parsel==1.8.1
Protego==0.3.0
pyarrow==13.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyDispatcher==2.0.7
pyOpenSSL==23.2.0
python-dateutil==2.8.2
pytz==2023.3.post1
queuelib==1.6.2
requests==2.31.0
requests-file==1.5.1
requests-oauthlib==1.3.1
Scrapy==2.11.0
service-identity==23.1.0
six==1.16.0
tldextract==3.6.0
Twisted==22.10.0
twython==3.9.1
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.5
w3lib==2.1.2
zope.interface==6.0

**Comment by eliasdabbas** [comment]
Sorry, it's not clear what might be causing this. 

A while ago there was an issue with pyoenssl, maybe try:

`pip install pyOpenSSL==22.0.0` and see if it works?

**Comment by mcgaleti** [comment]
Hi Elias, no need sorry! 

It didn't work too. 

Linux is complicated! Many Dependencies and etc. I got your AMAZING tool working on Google Colab and that is perfectly fine.

Thank you !!!!!!!!!!!!!!!!!!!!! I close this ticket as the issue is probably here.

Thank you so much

**Comment by eliasdabbas** [comment]
Great to know it's working on Colab! 
Enjoy and let me know if you get other issues.
