### ISSUE TITLE
Pandas Futurewarning "fillna" in url_to_df()

### ISSUE THREAD

**Issue by Dibal** [eliasdabbas/advertools#336]
Method: adv.url_to_df()
>>>
advertools/urlytics.py:198: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  .assign(last_dir=dirs_df

**Comment by eliasdabbas** [comment]
Thanks. 
Already fixed, will be out in the next release soon.
