### ISSUE TITLE
about this result in serp

### ISSUE THREAD

**Issue by wanghaisheng** [eliasdabbas/advertools#355]
https://blog.google/products/search/about-search-results/
can we get this part of info for each serp

**Comment by eliasdabbas** [comment]
As far as I know, I don't think so. 

Here are the full available parameters: https://developers.google.com/custom-search/v1/reference/rest/v1/cse/list

**Comment by wanghaisheng** [comment]
check this 


    url ="https://www.google.com/search/about-this-result?ri=CgwSCgoGY29mZmVlEAMSAggBGgIIASIAKgAyBggDEgJ1czoAQgQIARAASgBaAGoAcgA&url=https%3A%2F%2Fwww.remini.com&hl=en_US&gl=US"
    url ="https://www.google.com/search/about-this-result?url=https%3A%2F%2Fwww.remini.com&hl=en_US&gl=US"

**Comment by eliasdabbas** [comment]
That's a great idea. You can construct the URL that you want, and crawl it with the `crawl` function, and extract the information you want.

**Comment by eliasdabbas** [comment]
Assuming this was resolved.
