### ISSUE TITLE
logs_to_df

### ISSUE THREAD

**Issue by Dibal** [eliasdabbas/advertools#367]
Reading log file via
```
adv.logs_to_df(
    log_format=  'common', 
   errors_file="log_errors.csv",
...)
```
fills "log_errors.csv" with errors -- no surprise because mismatch of format.

But logs.to_df cannot process any user-defined regular expression string.

Example 1:
```
mycom = adv.logs.LOG_FORMATS['common']
adv.logs_to_df(
    log_format= mycom, 
   errors_file="log_errors.csv",
...)
```
does not fill "log_errors.csv" but throw Python error message:
"KeyError: ..."

Example 2:
Define correct mycom-string and test it successfully via:
`df['line'] = str.extract(mycom, expand=True)`
This regex-string does not work either.

Example 3:
`adv.logs.LOG_FORMATS['mycom'] = mycom`
fails as well.

**Comment by eliasdabbas** [comment]
Thanks for reporting.

Can you please share the log file that you are working on so I can check? Also please share the full code.

**Comment by Dibal** [comment]
Independent of the log file: 
(1) `log_format=  'common'`
and
(2) `log_format= adv.logs.LOG_FORMATS['common'] `
should be identical.

In (1) the program runs smoothly processing the data as good as possible (*).
In (2) the program terminates and throws a key error:
"KeyError: '^(?P<client>\\S+) \\S+ (?P<userid>\\S+) \\[(?P<datetime>[^\\]]+)\\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-)$'"

(*)
FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  final_df["datetime"] = pd.to_datetime(

PS: 
Pandas understands (zip-) compressed CSV files, logs_to_df() unfortunately not.

**Comment by eliasdabbas** [comment]
Thanks again. I need to see the log file please as I mentioned. Just a sample of lines, no need for the whole thing. 

Also, please share the full code these are scattered snippets here and there, I need the full thing to see what is happening. 

The KeyError is for the regular expression. Which code is causing that error?

**Comment by Dibal** [comment]
I would like to recognize those entries which failed by "common", eg:

164@@92.86.74.170 - - [19/Jul/2012:13:45:38 +0300] "-" 408 -@@list index out of range
308@@188.37.250.71 - - [25/Jul/2012:00:15:26 +0300] "\x16\x03\x01" 200 4481@@list index out of range
309@@188.37.250.71 - - [25/Jul/2012:00:15:45 +0300] "\x16\x03\x01" 200 4481@@list index out of range
310@@188.37.250.71 - - [25/Jul/2012:00:16:26 +0300] "\x16\x03\x01" 200 4481@@list index out of range

What I did: I took the regex string you offer in "common" and wanted to adapt it. I foud out: any regex-string I hand over gives "key error", even the "common" string itself.

**Comment by eliasdabbas** [comment]
This is the error file and not the log file. 

You can read this file with `pd.read_csv("your_filepath.csv", sep="@@")` you might use `names=["column1", "column2", "column3"]` (or whatever you want to call them).

You should get three columns, line number, log line, error message.

**Comment by Dibal** [comment]
~~~
188.27.250.71 - - [25/Jul/2012:00:18:59 +0300] "\x16\x03\x01" 200 4481
188.27.250.71 - - [25/Jul/2012:00:21:57 +0300] "\x16\x03\x01" 200 4481
127.0.0.1 - - [25/Jul/2012:01:34:42 +0300] "GET /phpmyadmin/ HTTP/1.1" 200 2576
127.0.0.1 - - [25/Jul/2012:01:34:42 +0300] "GET /phpmyadmin/main.php?token=f934fc58177f192f915319ecd0ada9ab HTTP/1.1" 200 37290
127.0.0.1 - - [25/Jul/2012:01:34:42 +0300] "GET /phpmyadmin/navigation.php?token=f934fc58177f192f915319ecd0ada9ab HTTP/1.1" 200 5059
~~~

Please let me summarize:

Your regex "common" processes the logfile correctly. But I had the idea to collect "errors" as well. This could be done by defining own regex-string.
But all my attempts failed -- but the "common"-string as a string failed as well.

Another remark: 
you took care about a lot of details: 
you assign date correctly (*), you categorize "method" and "status", you even converted "size" to numbers and removed entries like "-". Great!

(*) 
I prefer UTC and postprocessed `to_datetime(df['datetime'], utc=True)` (or simply "%z" in case date is still a string).

**Comment by Dibal** [comment]
Another remark: can you interpret the entry like `"\x16\x03\x01" 200 4481` ? What kind of method is it that it is even confirmed by "200"?

**Comment by eliasdabbas** [comment]
> Your regex "common" processes the logfile correctly. But I had the idea to collect "errors" as well. This could be done by defining own regex-string. But all my attempts failed -- but the "common"-string as a string failed as well.


That's a great idea.
What you can do, is:

1. Read the errors file in a DataFrame (as I mentioned above)
2. Extract the log lines column
3. Save the log lines to a new text file
4. Run `logs_to_df` with a new regex on that error file

The "common" string will definitely fail on those lines, because by definition, this is the error file that didn't match that pattern. So you'll need a new regex for them.

> Another remark: you took care about a lot of details: you assign date correctly (*), you categorize "method" and "status", you even converted "size" to numbers and removed entries like "-". Great!

Thanks! 

 
> (*) I prefer UTC and postprocessed `to_datetime(df['datetime'], utc=True)` (or simply "%z" in case date is still a string).

Cool. 
Keep in mind that in the new version 0.15.1 you have a new parameter `date_format` where you can change the format. If there is something that can be improved there, please let me know.

> Another remark: can you interpret the entry like "\x16\x03\x01" 200 4481 ? What kind of method is it that it is even confirmed by "200"?

These are bytes and not text. I'm not sure if there is a straightforward way to decode them. I really don't know.

**Comment by Dibal** [comment]
> The "common" string will definitely fail on those lines, because by definition, this is the error file that didn't match that pattern. So you'll need a new regex for them.

This is the point: `logs_to_df()` refuses any regex-string. It only accept key words like "common".

**Comment by eliasdabbas** [comment]
When you provide a custom regex string, the function doesn't know how many fields your log file has, and doesn't know what to name these columns.

When providing a custom regex you need to supply the `fields` argument, and these become the column names

```bash
Parameters
----------
log_file : str
  The path to the log file.
output_file : str
  The path to the desired output file. Must have a ".parquet" extension, and must
  not have the same path as an existing file.
errors_file : str
  The path where the parsing errors are stored. Any text format works, CSV is
  recommended to easily open it with any CSV reader with the separator as "@@".
log_format : str
  The name of one of the supported log formats, or a regex of your own format.
######################################
fields : list
  A list of fields, which will become the names of columns in ``output_file``. Only
  required if you provide a custom (regex) ``log_format``.
######################################
encoding : str
  The encoding of the log file. It defaults to utf-8, but you might need to try
  others in case of errors (latin-1, utf-16, etc.)
```

**Comment by Dibal** [comment]
> When providing a custom regex you need to supply the fields argument, and these become the column names

Now I understand why you did not understand me: your script expect another parameter which was obvious for you but not me.

But why this list? Aren't the named regex fields sufficient?

I run this code successfully (`df` has one field and each row is one full line of input file):

~~~
myregs = r'^(?P<client>\S+) \S+ (?P<userid>\S+) \[(?P<datetime>[^\]]+)\] "(?P<method>[A-Z]+) (?P<request>[^ "]+)? HTTP/[0-9.]+" (?P<status>[0-9]{3}) (?P<size>[0-9]+|-).*$'
df['Line'].str.extract(myregs, expand=True)
~~~
... and new dataframe get all the fields named in regex above (ie: client userid 	datetime method request status size).

**Comment by eliasdabbas** [comment]
> Now I understand why you did not understand me: your script expect another parameter which was obvious for you but not me.

True. But I would have understood from the first question if you provided the full code and an example log file with a full reproducible example.

> But why this list? Aren't the named regex fields sufficient?

Named fields are optional in regex. I include them for clarity but most users might not include them.

**Comment by Dibal** [comment]
I see. This is what you requested for:

~~~
mycom = ((my regex expression here))
adv.logs_to_df(
    log_file=fn,
    output_file=fno,
    errors_file="temp_log_errors.csv",
    log_format= mycom, #'common'
    fields=None,
)
~~~

And I learned that the parameter `fields` is mandatory even if I specify field in regex expression.

Thanks. 
Should I close discussion?

**Comment by Dibal** [comment]
Final remark:

Dumb users like me assume that a string like `myreg = adv.logs.LOG_FORMATS['common']` should be accepted by `logs_to_df`. This is not the case; now another parameter `fields` is required.

What about a check for named groups?

`fields = re.findall('\(\?P<(.*?)>', myreg)`

**Comment by eliasdabbas** [comment]
Thans @Dibal

I'm thinking of raising an error when the user provides a custom regex without providing the fields, and hopefully making it clear what went wrong, with a clear message.

Your feedback is important, so please keep providing it. It helps a lot.

A check for named groups (a regex that checks another regex) might make things a bit more complicated than they should be.

If you have other issues or suggestions please share them. I'll close this for now.
