### ISSUE TITLE
Crawling big website - Memory leak? 

### ISSUE THREAD

**Issue by antoineeripret** [eliasdabbas/advertools#386]
Hello @eliasdabbas , 

I'm trying to crawl a big website (>1M URLs) and the process is basically killing my computer and I'm unsure why. It may be linked to [Scrapy memory leak](https://docs.scrapy.org/en/2.11/topics/leaks.html) but I wanted to double check with you. 

For reference, this is the code used: 

```python
import advertools as adv 

#the domain we want to crawl 
domain = 'https://www.example.com/'
#we launch the crawl 
adv.crawl(
    domain, 
    output_file='crawl_results.jl', 
    follow_links = True, 
    allowed_domains = ['www.example.com'],
    xpath_selectors={
        #meta robots tag 
        'meta_robots': '//meta[@name="robots"]/@content',
    }, 
    custom_settings={
        'DEPTH_LIMIT': 10,
        #maximum of 10 requests per second
        'DOWNLOAD_DELAY': 0.1,
        'EXCLUDE_URLS': '/blog/',
        'JOBDIR': '/crawl_data/temp',
    }
)

``` 

I'm using a computer with 16GB of RAM and after a bit more than 5k URLs crawled / parsed, my Jupyter Notebook (ran through VS Code) **was using more than 14GB.**

```python 
 'memusage/max': 140787712,
```

My assumption is that even though only 5k pages were crawled, **the crawling queue is huge and that's what may create the issue.** If this is indeed the case, do you know how I can mitigate this issue to crawl the website with your library?  

Thank you very much !

**Comment by eliasdabbas** [comment]
Thanks a lot @antoineeripret 

Great to know you're using it for a large website. I'd love to know how it goes.

The memory consumption is usually very small because crawled pages are saved to disk, and free memory continuously. 

In your case it seems that the logs are clogging the jupyter notebook, and that's probably why it's taking up so much memory. 5k is still a tiny number of URLs.

You can easily set the `LOG_FILE` custom setting as shown below, which should solve the issue:

```python
adv.crawl(
    domain, 
    output_file='crawl_results.jl', 
    follow_links = True,
    # you can use this option to exclude URL patterns:
    exclude_url_regex='/blog/',
    allowed_domains = ['www.example.com'],
    xpath_selectors={
        #meta robots tag 
        'meta_robots': '//meta[@name="robots"]/@content',
    }, 
    custom_settings={
        'LOG_FILE': 'crawl_logs.log',
        'DEPTH_LIMIT': 10,
        #maximum of 10 requests per second
        'DOWNLOAD_DELAY': 0.1,
 # I'm not sure this is a scrapy option
 #       'EXCLUDE_URLS': '/blog/',
        'JOBDIR': '/crawl_data/temp',
    }
)
```

Please let me know how it went, and I'm happy to look again if the issue persists.
Thanks again!

**Comment by antoineeripret** [comment]
Hi @eliasdabbas, 

I'll launch it again and let you know how it goes. 

Thank you !

**Comment by antoineeripret** [comment]
Hi @eliasdabbas, 

The crawl if far from being finished, but your solution has fixed the underlying issue. VS Code is using less than 2GB at the moment, and the crawl has been going for a couple of hours already. 

Thank you! 

I'll close the issue and open it again if needed :)

**Comment by eliasdabbas** [comment]
@antoineeripret Perfect!

Let me know when you get to the analysis phases, it's probably going to be a very large file, there are a few tools/techniques for that if you want.

Check the [adv.crawlytics](https://advertools.readthedocs.io/en/master/advertools.crawlytics.html) module for some ideas. Happy to help as well.

**Comment by antoineeripret** [comment]
I might use [Polars](https://pola.rs/) for this one, Pandas is indeed struggling. I'll have a look at your code as well, thanks for linking it :)  

![image](https://github.com/user-attachments/assets/a0d19526-8bf1-4c5e-93c2-38e5d8af2b8e)
