### ISSUE TITLE
Missing 404 pages from links column

### ISSUE THREAD

**Issue by antoineeripret** [eliasdabbas/advertools#392]
Hello @eliasdabbas, 

I'm facing an issue and I'm not sure if I'm missing something or if the behavior is expected. 

So, I have a list of URLs in my crawl output with around 1,000 with a `status` of 404. I'm trying to understand where these links come from to remove/fix them, therefore I'm exploring the `links_` columns. 

For the context, **I have broken my crawl file down into several CSV files before and I'm using [Polars](https://pola.rs/).**  

```python 

( 
                pl 
                .read_csv(directory + file)
                .with_columns(
                    links_url = pl.col("links_url").str.split("@@"),
                )
                .explode("links_url")
                .rename(
                    {
                        "url": "from_url",
                        "links_url": "to_url"
                    }
                )
                .select(
                                    ['from_url', 'to_url']
               )
)
```

The data is then inserted into a [DuckDB](https://duckdb.org/) database through this function and a loop. This step is obviously not needed, but I found out that DuckDB is way faster than Polars / Pandas given the number of rows I have. 

```python 

def load_duckdb(df): 
    conn = duckdb.connect()
    conn.execute(
    ## this is executed just once, but adding it here to not copy paste all my logic in GitHub and 
    ## keep the ticket simple 
    "CREATE OR REPLACE TABLE links (from_url VARCHAR, to_url VARCHAR)"
   #this is executed for every run of the for loop 
    conn.execute("INSERT INTO links SELECT * from df")
```

After the load, the table contains around 75M rows, which makes sense given the crawl size. When I search for a given row out of the 404 subset I mentioned above: 

- I can find rows if I use the URL as a filter for the `url_from`. Usually two because that's the number of links displayed on our 404 template. Perfect ! 
- I cannot find anything if I use the URL as a filter for the `url_to` (`=` or `like` to account for parameters, FYI) 

I don't understand why. If they are in the crawl file, they must be linked from somewhere, right? Or are they filtered automatically given that they are not returning 200? 

Thank you !

**Comment by eliasdabbas** [comment]
Thanks @antoineeripret 
I'm assuming you want to locate the links to the 404 pages?

If so, there is a `links` function in the `crawlytics` module:

```python
link_df = adv.crawlytics.links(crawldf, internal_url_regex='nytimes.com')
link_df
```

|    | url                                                                                          | link                                                                                                      | text               | nofollow   | internal   |
|---:|:---------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------|:-------------------|:-----------|:-----------|
|  0 | https://www.nytimes.com/interactive/2020/03/03/us/elections/exit-polls-oklahoma-primary.html | https://www.nytimes.com/interactive/2020/03/03/us/elections/exit-polls-oklahoma-primary.html#site-content | Skip to content    | False      | True       |
|  0 | https://www.nytimes.com/interactive/2020/03/03/us/elections/exit-polls-oklahoma-primary.html | https://www.nytimes.com/interactive/2020/03/03/us/elections/exit-polls-oklahoma-primary.html#site-index   | Skip to site index | False      | True       |
|  0 | https://www.nytimes.com/interactive/2020/03/03/us/elections/exit-polls-oklahoma-primary.html | https://www.nytimes.com/topic/subject/elections                                                           | Elections          | False      | True       |
|  1 | https://www.nytimes.com/interactive/2021/us/tioga-new-york-covid-cases.html                  | https://www.nytimes.com/interactive/2021/us/tioga-new-york-covid-cases.html#site-content                  | Skip to content    | False      | True       |
|  1 | https://www.nytimes.com/interactive/2021/us/tioga-new-york-covid-cases.html                  | https://www.nytimes.com/interactive/2021/us/tioga-new-york-covid-cases.html#site-index                    | Skip to site index | False      | True       |
|  1 | https://www.nytimes.com/interactive/2021/us/tioga-new-york-covid-cases.html                  | https://www.nytimes.com/section/us                                                                        | U.S.               | False      | True       |
|  2 | https://www.nytimes.com/interactive/2021/us/ferry-washington-covid-cases.html                | https://www.nytimes.com/interactive/2021/us/ferry-washington-covid-cases.html#site-content                | Skip to content    | False      | True       |
|  2 | https://www.nytimes.com/interactive/2021/us/ferry-washington-covid-cases.html                | https://www.nytimes.com/interactive/2021/us/ferry-washington-covid-cases.html#site-index                  | Skip to site index | False      | True       |
|  2 | https://www.nytimes.com/interactive/2021/us/ferry-washington-covid-cases.html                | https://www.nytimes.com/section/us                                                                        | U.S.               | False      | True       |
|  3 | https://www.nytimes.com/interactive/2021/us/hernando-florida-covid-cases.html                | https://www.nytimes.com/interactive/2021/us/hernando-florida-covid-cases.html#site-content                | Skip to content    | False      | True       |
|  3 | https://www.nytimes.com/interactive/2021/us/hernando-florida-covid-cases.html                | https://www.nytimes.com/interactive/2021/us/hernando-florida-covid-cases.html#site-index                  | Skip to site index | False      | True       |
|  3 | https://www.nytimes.com/interactive/2021/us/hernando-florida-covid-cases.html                | https://www.nytimes.com/section/us                                                                        | U.S.               | False      | True       |

This gives a mapping of all link with a few other meta data. The `internal_url_regex` parameter is optional but it's good to separate internal/external links. 

Then you can filter:

```python
error_urls = crawldf[crawldf['status'].eq(404)]['url']
link_df[link_df['link'].isin(error_urls)]
```

Filters the `link_df` to rows where the target link is a 404 (or whatever condition you want).

Does this solve it?

**Comment by antoineeripret** [comment]
Hi @eliasdabbas, 

> I'm assuming you want to locate the links to the 404 pages?
Exactly ! 

I'm using a very similar function to 

```python 
link_df = adv.crawlytics.links(crawldf, internal_url_regex='nytimes.com')
```

But through Polars / DuckDB for performance reasons. 

Now, I've used your module because I understand that it eases debugging as you don't have access at my code / data :) 

```python 

url_to_find = "https://www.example.com/my_url_returning_404"

craw_output = "crawl_results.jl"

for i, chunk in enumerate(pd.read_json(craw_output, lines=True, chunksize=10000)):
        links = adv.crawlytics.links(chunk, internal_url_regex='example.com')
        df_filter = (
            links 
            .query("url == @url_to_find or link == @url_to_find")
        )
        if len(df_filter) > 0:
            print("found")
            df_filter.to_csv(f"check_{i}.csv") 
        else: 
              print("not found")

```
The output is one file with two lines, the `url_to_find` being the value for `url`, never `link`. This is why I suspect that 404 are somehow removed from the link columns. 

FWIW, the `url_to_find` is in the `crawl_results.jl` file (`url` column) and the depth is > 0. 

Thank you !

**Comment by eliasdabbas** [comment]
Great! Good to have a recipe for it for large datasets!

**Comment by antoineeripret** [comment]
Hello @eliasdabbas, 

I wanted to double-check: do you confirm then that 404 are indeed removed from the links column? 

> The output is one file with two lines, the url_to_find being the value for url, never link. This is why I suspect that 404 are somehow removed from the link columns

As explained in my previous message, Impossible to find my url in the link column. Is it because it's not returning 200? 

Thanks!

**Comment by eliasdabbas** [comment]
I don't think any 404s will be removed from the column, nothing is being changed in the links data frame.

It maybe that using the `.query` method is not catching it? I find it convenient, but sometimes limiting. 

I just tried replacing with the following: 

```python
df_filter = links[links['url'].eq(url_to_find) | links[links['link'].eq(url_to_find)]]
```

Typically, you'd want this for multiple values (all 404 pages and not just one), so I initially created a list of those URLs, then used `isin` to check:

```python
error_urls = crawldf[crawldf['status'].eq(404)]['url']
df_filter = links[links['url'].isin(error_urls) | links[links['link'].isin(error_urls)]]
```

It seems to work. 

Can you please try this and see?

**Comment by antoineeripret** [comment]
Hello @eliasdabbas, 

You're correct, it seems that you the library doesn't remove the 404 URLs, as I'm getting files with 

```python 
error_urls = crawldf[crawldf['status'].eq(404)]['url']
df_filter = links[links['url'].isin(error_urls) | links[links['link'].isin(error_urls)]]
```

I still have some rare cases where the page is missing though... What I realized is that all of them includes a `+` sign in the structure. For instance: 

`https://www.example.com/folder/this+is+strange-192`

Could the fact that they're missing be linked to that? 

Thank you !

**Comment by eliasdabbas** [comment]
Could be because the `+` sign is a special character in regex? (One or more of the previous character)

Maybe try to escape it `\+` and see if that works?

**Comment by antoineeripret** [comment]
No result returned either. Moreover, the `eq` method doesn't accept REGEX AFAIK 

Would it be simpler if I share the raw crawl file with you and a couple of examples? It's 30GB but I can upload it on my Drive (it's just a public crawl, so nothing confidential) and share the link with you. 

Thank you !

**Comment by eliasdabbas** [comment]
Yes, sorry, it should have been `.str.contains` and the regex should match the complete string.

Sure, I'd love to take a look.

You crawled 30GB with advertools?!

**Comment by antoineeripret** [comment]
Hi @eliasdabbas, 

> Yes, sorry, it should have been .str.contains and the regex should match the complete string.

Same outcome :( 

> You crawled 30GB with advertools?!

Yep ! And it would have been more, but I've limited the depth :)  Amazing tool you've built here and we aim at using it for a couple of things 👍 👍  !! 

> Sure, I'd love to take a look.

[Here](https://drive.google.com/file/d/1DyKzBgiob4kPNvjr-ugJv1oPWZO6k8VU/view?usp=sharing) you go. 

Some examples of 404 pages available in the file as rows (**url** column) but that I can't find in the **links** column (after [exploding](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html) it manually or using the [crawlytics module](https://advertools.readthedocs.io/en/master/advertools.crawlytics.html)) 

1. https://www.doctoralia.es/enfermedad/oxiuros-3041 (depth 5) 
2. https://www.doctoralia.es/enfermedad/eccema+numular-1231 (depth 9) 
3. https://www.doctoralia.es/enfermedad/otitis+media+aguda-3028 (depth 5) 
4. https://www.doctoralia.es/enfermedad/hipoglucemia-2129 (depth 10) 

- All are returning 404 
- I do have other 404 that I can find in the **links** columns (such as https://www.doctoralia.es/fisioterapeuta/mataro/ciutat-vella)

Thank you !

**Comment by eliasdabbas** [comment]
Improvement, but not fully


```python
# Read only the url and status columns
url_status = adv.crawlytics.jl_subset(path, columns=['url', 'status'], chunksize=1000)

# Get URLs where status is not equal to 200
error_urls = url_status[url_status['status'].ne(200)]['url'].tolist()

# Read only the url and links_url columns
url_links = adv.crawlytics.jl_subset(path, columns=['url', 'links_url'], chunksize=1000)
```

Now you can explode the new DataFrame

```python
links_exploded = pd.DataFrame({
    'url': url_links['url'],
    'link': url_links['links_url'].str.split('@@')
}).explode('link')
```

Now filter for rows where link is in `error_urls`

```python
links_exploded[links_exploded['link'].isin(error_urls)]
```

I got 333 rows here with 53 unique link URLs. 

- URL normalization: Maybe links contain fragments and/or trailing slashes? I checked, about 10% of them do, but didn't affect much finding the error links.

Maybe there are no links to those error URLs? But then how were they crawled/discovered?
Was the whole crawling process in spider mode, or did you start with XML sitemaps?

**Comment by antoineeripret** [comment]
> Maybe there are no links to those error URLs? But then how were they crawled/discovered?

This is the puzzle I'm trying to solve. If there is no filtering done on the **links** column based on the response code, I'm not sure why they are here. I've checked if these URLs were **canonical** of another **url**, and it is not the case either. So I'm not sure why they are here to be honest. 

This affects a small subset of found URLs, though. 

> Was the whole crawling process in spider mode, or did you start with XML sitemaps?

Here is the configuration used for this crawl. As you can see, only spider mode. 

```python 
#the domain we want to crawl 
domain = 'https://www.doctoralia.es/'
#we launch the crawl 
adv.crawl(
    domain, 
    output_file='crawl_results.jl', 
    follow_links = True, 
    allowed_domains = ['www.doctoralia.es'],
    exclude_url_regex='/blog/',
    xpath_selectors={
        #meta robots tag 
        'meta_robots': '//meta[@name="robots"]/@content',
    }, 
    custom_settings={
        'DEPTH_LIMIT': 10,
        #maximum of 10 requests per second
        'DOWNLOAD_DELAY': 0.1,
        'LOG_FILE': 'crawl_logs.log',

    }
)
```

**Comment by eliasdabbas** [comment]
Redirects?

Maybe there was a link to `URL_A`, and `URL_A` redirects to `URL_error_page`.

This might make sense, `URL_error_page` doesn't have links pointing to it (only redirects), but is an error page itself.

We can check through the `adv.crawlytics.redirects` function.

**Comment by antoineeripret** [comment]
@eliasdabbas, you're right !  

![image](https://github.com/user-attachments/assets/6699c360-6ea0-46c9-8206-2935f80b5585)

That explains everything. 

Thank you very much for your support, really appreciate it !

**Comment by eliasdabbas** [comment]
Great to hear this!

For reference, here are the steps to check:

Read a subset of the redirect columns:

```python
redirect_columns = adv.crawlytics.jl_subset(
    CRAWL_FILE_PATH,
    columns=["url", "status", "redirect_urls", "redirect_reasons", "download_latency", "redirect_times"])
```

Create the redirect DataFrame

```python
redirect_df = adv.crawlytics.redirects(redirect_columns)
redirect_df # sample rows
```
|       | url                                                           |   status |   order | type         |   download_latency |   redirect_times |
|------:|:--------------------------------------------------------------|---------:|--------:|:-------------|-------------------:|-----------------:|
| 41823 | http://www.doctoralia.es/s/broncodilatador                    |      301 |       1 | requested    |           0.182104 |                1 |
| 41823 | https://www.doctoralia.es/s/broncodilatador                   |      404 |       2 | crawled      |           0.182104 |                1 |
| 41827 | http://www.doctoralia.es/enfermedad/gripe-1886                |      301 |       1 | requested    |           0.439063 |                2 |
| 41827 | https://www.doctoralia.es/enfermedad/gripe-1886               |      301 |       2 | intermediate |           0.439063 |                2 |
| 41827 | https://www.doctoralia.es/enfermedades/gripe                  |      200 |       3 | crawled      |           0.439063 |                2 |
| 48074 | http://www.doctoralia.es/enfermedad/dermatitis+alergica-1043  |      301 |       1 | requested    |           0.152113 |                1 |
| 48074 | https://www.doctoralia.es/enfermedad/dermatitis+alergica-1043 |      404 |       2 | crawled      |           0.152113 |                1 |
| 48080 | http://www.doctoralia.es/enfermedad/foliculitis-1759          |      301 |       1 | requested    |           0.269555 |                1 |
| 48080 | https://www.doctoralia.es/enfermedad/foliculitis-1759         |      404 |       2 | crawled      |           0.269555 |                1 |
| 48082 | http://www.doctoralia.es/enfermedad/otitis-3022               |      301 |       1 | requested    |           0.183204 |                1 |
| 48082 | https://www.doctoralia.es/enfermedad/otitis-3022              |      404 |       2 | crawled      |           0.183204 |                1 |
| 48083 | http://www.doctoralia.es/s/antibiotico-y-corticoide-otologico |      301 |       1 | requested    |           0.191739 |                1 |

Index of 404 pages
```python
index_404 = redirect_df[redirect_df['status'].eq(404)].index
```

Full redirects (including all URLs for each redirect and metadata):

```python
redirect_df.loc[index_404, :]
```

- Test: Are these related to the `error_urls` that we found by checking with rows have a status of 404?
Using set operations we can compare the difference between error_urls (the original reference dataset) and the ones we just found (there should be none):

```python
set(redirect_df[redirect_df['status'].eq(404)]['url'].drop_duplicates()).difference(error_urls)
set()
```

We should make a case study/tutorial on how to investigate such issues (not straightforward), especially with such a large crawl file.

**Comment by eliasdabbas** [comment]
Another observation:
Most of these redirects are from the http version to the https version of the same URL. So it's not really a "redirect" to another page. 
<img width="808" alt="Screenshot 2024-11-20 at 3 33 59 PM" src="https://github.com/user-attachments/assets/f5833de8-2575-4a0c-a58d-b359aee2f7b0">

This means we should make sure that the regular links themselves are also modified to go to the https version.

More formally:
```python
# get shape of the url column

redirect_df.loc[index_404, :]['url'].shape
(1876,)

# Count unique URLs
redirect_df.loc[index_404, :]['url'].nunique()
1876

# Replشce "http://" with "https://" and count uniques
redirect_df.loc[index_404, :]['url'].str.replace('http://', 'https://').nunique()
971 # this is less than 992 which means we didn't miss anything
```

**Comment by antoineeripret** [comment]
Hi @eliasdabbas, 

Thank you for the code snippets, I'll save them !  

Regarding 

> We should make a case study/tutorial on how to investigate such issues (not straightforward), especially with such a large crawl file.

Happy to help if you need me :) 

> Most of these redirects are from the http version to the https version of the same URL. So it's not really a "redirect" to another page.

So here, couldn't we slightly modify the way the library works? IMO, a link through a redirect (a "real" redirect or http to https) is still a link (because this is how the page has been discovered) and we should have a **link_type** column with the following possible values: 

```python 
["AHREF", "REDIRECT"]
```

Otherwise we need to bundle a serie of methods together to get the information and understand where these URLs come from. 

What do you think? Edge-case not worth considering? Worth it? 

Thanks,

**Comment by eliasdabbas** [comment]
> Happy to help if you need me :)

Great! I'll DM you separately.

> we should have a link_type column

Interesting. 

Redirects can contain multiple URLs, in which case which link are we referring to (first, second, last...?). Also, each one has its own status code, so we can analyze the full chain.

That's the main tricky part, and that's why redirects have their own function through which we can discover these things.

An easy solution is to quickly check for rows where `redirect_urls` is not None, and see if there's something there.

What do you think?

**Comment by antoineeripret** [comment]
> Redirects can contain multiple URLs, in which case which link are we referring to (first, second, last...?). Also, each one has its own status code, so we can analyze the full chain.That's the main tricky part, and that's why redirects have their own function through which we can discover these things.

Fair enough ! Can't think of a simple solution to be honest, therefore I'd rather leave the library as it is right now and play with the available modules :) 

Thanks a lot for your help, really appreciate it ! I'll answer your DM when I have a moment.
