### ISSUE TITLE
serp_goog next page

### ISSUE THREAD

**Issue by antonmadjid** [eliasdabbas/advertools#58]
hi sir,
I am having problems with the start parameter on serp_goog. I want to query from the first page to the 4th.
Please advise.
thank you
packages version:
pandas
In [5]: print(pd.__version__)
0.25.0
advertools
In [6]: print(adv.__version__)
0.7.3
----> 4 next_result_1=adv.serp_goog(cx=cx, key=key, q=queri, gl=['id'],start=[1, 11, 21])
KeyError: "['start'] not in index"

C:\Anaconda3\lib\site-packages\advertools\serp.py in serp_goog(q, cx, key, c2coff, cr, dateRestrict, exactTerms, excludeTerms, fileType, filter, gl, highRange, hl, hq, imgColorType, imgDominantColor, imgSize, imgType, linkSite, lowRange, lr, num, orTerms, relatedSite, rights, safe, searchType, siteSearch, siteSearchFilter, sort, start)
    700                     specified_cols)
    701     non_ordered = result_df.columns.difference(set(ordered_cols))
--> 702     final_df = result_df[ordered_cols + list(non_ordered)]
    703     return final_df
    704 

C:\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2979             if is_iterator(key):
   2980                 key = list(key)
-> 2981             indexer = self.loc._convert_to_indexer(key, axis=1, raise_missing=True)
   2982 
   2983         # take() does not accept boolean indexers

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py in _convert_to_indexer(self, obj, axis, is_setter, raise_missing)
   1269                 # When setting, missing keys are not allowed, even with .loc:
   1270                 kwargs = {"raise_missing": True if is_setter else raise_missing}
-> 1271                 return self._get_listlike_indexer(obj, axis, **kwargs)[1]
   1272         else:
   1273             try:

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py in _get_listlike_indexer(self, key, axis, raise_missing)
   1076 
   1077         self._validate_read_indexer(
-> 1078             keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
   1079         )
   1080         return keyarr, indexer

C:\Anaconda3\lib\site-packages\pandas\core\indexing.py in _validate_read_indexer(self, key, indexer, axis, raise_missing)
   1169             if not (self.name == "loc" and not raise_missing):
   1170                 not_found = list(set(key) - set(ax))
-> 1171                 raise KeyError("{} not in index".format(not_found))
   1172 
   1173             # we skip the warning on Categorical/Interval

KeyError: "['start'] not in index"

**Comment by eliasdabbas** [comment]
Thanks for reporting.  
You are using it correctly, and it's a bug that was solved just yesterday :)

Please upgrade to versin 0.7.4.

Let me know if you still have any issues.

**Comment by antonmadjid** [comment]
thank you for the quick response. I tried and everything went well.
I will try all the features of advertools and report them.

thank you sir.
