### ISSUE TITLE
`sitemap_to_df` wrongly handles multiple video tags

### ISSUE THREAD

**Issue by eliasdabbas** [eliasdabbas/advertools#87]
[Video sitemaps](https://support.google.com/webmasters/answer/80471?hl=en&ref_topic=4581190) allow multiple \<video:tag> elements in a sitemap entry. `sitemap_to_df` only handles the last given tag. It should extract all of them.

**Comment by chbg** [comment]
@eliasdabbas , is this still an issue?

**Comment by eliasdabbas** [comment]
@chbg Unfortunately, yes.

It would require a re-write, and I haven't found the time. Hopefully soon. Any contributions/suggestions are welcomed of course.
